import { useState, useEffect } from 'react';
import { Button } from './ui/Button';
import { Input } from './ui/Input';
import { Label } from './ui/Label';
import { Key, Plus, Trash2, Copy, RefreshCw, AlertCircle } from 'lucide-react';
import { invoke } from '@tauri-apps/api/core';
import { toast } from '../store/toastStore';

interface SshKey {
  key_type: string;
  path: string;
  public_key: string;
  has_private_key: boolean;
  created_at: string | null;
}

export function SSHKeyManager() {
  const [sshKeys, setSshKeys] = useState<SshKey[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [showGenerateForm, setShowGenerateForm] = useState(false);
  const [email, setEmail] = useState('');
  const [keyType, setKeyType] = useState('ed25519');
  const [isGenerating, setIsGenerating] = useState(false);

  const loadSshKeys = async () => {
    setIsLoading(true);
    try {
      const keys = await invoke<SshKey[]>('get_ssh_keys');
      setSshKeys(keys);
    } catch (error) {
      console.error('Failed to load SSH keys:', error);
      toast.error('加载SSH密钥失败');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    loadSshKeys();
  }, []);

  const handleGenerateKey = async () => {
    if (!email) {
      toast.error('请输入邮箱地址');
      return;
    }

    setIsGenerating(true);
    try {
      const publicKey = await invoke<string>('generate_ssh_key', {
        email,
        keyType,
        comment: `Generated by GAT`,
      });

      toast.success('SSH密钥生成成功');
      setShowGenerateForm(false);
      setEmail('');
      
      // Copy public key to clipboard
      await navigator.clipboard.writeText(publicKey);
      toast.info('公钥已复制到剪贴板，可以添加到Git服务器');
      
      await loadSshKeys();
    } catch (error) {
      console.error('Failed to generate SSH key:', error);
      toast.error(`生成SSH密钥失败: ${error}`);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDeleteKey = async (keyType: string) => {
    try {
      await invoke('delete_ssh_key', { keyType });
      toast.success('SSH密钥删除成功');
      await loadSshKeys();
    } catch (error) {
      console.error('Failed to delete SSH key:', error);
      toast.error(`删除SSH密钥失败: ${error}`);
    }
  };

  const handleCopyPublicKey = async (publicKey: string) => {
    try {
      await navigator.clipboard.writeText(publicKey);
      toast.success('公钥已复制到剪贴板');
    } catch (error) {
      toast.error('复制失败');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h4 className="text-sm font-medium">SSH 密钥管理</h4>
        <Button
          size="sm"
          variant="outline"
          className="h-7 gap-1.5 text-xs"
          onClick={loadSshKeys}
          disabled={isLoading}
        >
          <RefreshCw className={`w-3.5 h-3.5 ${isLoading ? 'animate-spin' : ''}`} />
          刷新
        </Button>
      </div>

      {/* Generate Key Form */}
      {showGenerateForm ? (
        <div className="p-4 bg-muted/30 rounded-lg space-y-4">
          <h5 className="text-sm font-medium">生成新的SSH密钥</h5>
          
          <div className="space-y-2">
            <Label>邮箱地址</Label>
            <Input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="your-email@example.com"
            />
          </div>

          <div className="space-y-2">
            <Label>密钥类型</Label>
            <select
              value={keyType}
              onChange={(e) => setKeyType(e.target.value)}
              className="w-full px-3 py-2 bg-background border border-border rounded-md"
            >
              <option value="ed25519">ED25519 (推荐)</option>
              <option value="rsa">RSA (4096位)</option>
              <option value="ecdsa">ECDSA</option>
            </select>
          </div>

          <div className="flex gap-2">
            <Button
              onClick={handleGenerateKey}
              disabled={isGenerating || !email}
              className="flex-1"
            >
              {isGenerating ? '生成中...' : '生成密钥'}
            </Button>
            <Button
              variant="ghost"
              onClick={() => setShowGenerateForm(false)}
              disabled={isGenerating}
            >
              取消
            </Button>
          </div>
        </div>
      ) : (
        <Button
          variant="outline"
          className="w-full"
          onClick={() => setShowGenerateForm(true)}
        >
          <Plus className="w-4 h-4 mr-2" />
          生成新的SSH密钥
        </Button>
      )}

      {/* SSH Keys List */}
      <div className="space-y-3">
        {sshKeys.length === 0 && !isLoading && (
          <div className="p-4 bg-muted/30 rounded-lg text-center text-sm text-muted-foreground">
            暂无SSH密钥
          </div>
        )}

        {sshKeys.map((key) => (
          <div
            key={key.key_type}
            className="p-4 bg-muted/30 rounded-lg space-y-3"
          >
            <div className="flex items-start justify-between">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-1">
                  <Key className="w-4 h-4 text-primary" />
                  <span className="text-sm font-medium uppercase">
                    {key.key_type}
                  </span>
                  {key.has_private_key && (
                    <span className="text-xs px-2 py-0.5 bg-green-500/10 text-green-600 rounded-full">
                      有私钥
                    </span>
                  )}
                </div>
                <p className="text-xs text-muted-foreground">
                  路径: {key.path}
                </p>
              </div>

              <div className="flex gap-1">
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-7 w-7 p-0"
                  onClick={() => handleCopyPublicKey(key.public_key)}
                  title="复制公钥"
                >
                  <Copy className="w-3.5 h-3.5" />
                </Button>
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-7 w-7 p-0 text-destructive hover:text-destructive"
                  onClick={() => handleDeleteKey(key.key_type)}
                  title="删除密钥"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </Button>
              </div>
            </div>

            <div className="p-2 bg-background rounded border border-border">
              <p className="text-xs text-muted-foreground mb-1">公钥:</p>
              <p className="text-xs font-mono break-all">{key.public_key}</p>
            </div>

            {key.created_at && (
              <p className="text-xs text-muted-foreground">
                创建时间: {new Date(key.created_at).toLocaleString('zh-CN')}
              </p>
            )}
          </div>
        ))}
      </div>

      <div className="p-3 bg-blue-500/10 border border-blue-500/30 rounded-md">
        <div className="flex gap-2">
          <AlertCircle className="w-4 h-4 text-blue-600 dark:text-blue-400 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="text-xs text-blue-700 dark:text-blue-300">
              <strong>使用SSH密钥:</strong> 生成密钥后，将公钥添加到GitHub、GitLab等Git服务器的SSH密钥设置中。私钥将保存在 ~/.ssh/ 目录下。
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
